### ISSUE TITLE
Getting error while persisting Point Data

### ISSUE THREAD

**Issue by punit412** [mstahv/spring-boot-spatial-example#3]
Using same code and getting below error. Using Mysql 5.7 + and Java 8 

Hibernate: insert into spatial_event (version, date, location, route, title) values (?, ?, ?, ?, ?)
Hibernate: insert into spatial_event (version, date, location, route, title) values (?, ?, ?, ?, ?)
Jul 04, 2017 5:23:43 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions
ERROR: Data truncation: Cannot get geometry object from data you send to the GEOMETRY field
[main] INFO org.springframework.boot.autoconfigure.logging.AutoConfigurationReportLoggingInitializer - 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
[main] ERROR org.springframework.boot.SpringApplication - Application startup failed
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:803)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:784)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:771)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
	at org.vaadin.example.SpatialSpringBootAppApplication.main(SpatialSpringBootAppApplication.java:15)

**Comment by pushpanktugnawat** [comment]
I am even facing the same problem while persisting the Point as well as Geometry data type.

Please help to resolve this ASAP.

**Comment by pushpanktugnawat** [comment]
@mstahv Please help to resolve this I have done this with same configuration as provided in code but still it causes the same problem.

Your kind help is appreciated.

**Comment by punit412** [comment]
Hello @mstahv , Please reply i you have some solution for the above-mentioned issue.

**Comment by mstahv** [comment]
I don't have the project open ATM and don't remember what column type was required by MySQL. Try changing the column type from "geometry" to "POINT": https://github.com/mstahv/spring-boot-spatial-example/blob/master/src/main/java/org/vaadin/example/SpatialEvent.java#L21-L22

**Comment by punit412** [comment]
Already changes as per your comment. Still, the same issue occurred. Please suggest.

**Comment by pushpanktugnawat** [comment]
@mstahv  Thanks for reply ! we did the same but issue still persist. Please suggest a way to solve this as its causing the same issue as mentioned above again.

**Comment by mstahv** [comment]
I'd suggest to try with latest version of both database and hibernate. I'd need to re install MySQL to report a version that works for me.

**Comment by pushpanktugnawat** [comment]
We are working with latest DB version as well as Hibernate 5.1.0 which supports Spatial & JPA too. 

Pl help as its very critical to resolve such issues.

**Comment by pushpanktugnawat** [comment]
@mstahv any update on issue ??

**Comment by mstahv** [comment]
IIRC, the Hibernate version you use (the default by spring boot 1.x) is bad for mysql. Use 5.2 series in the project. I guess this is the issue you have had. I tried with mysql 5.7.17 and all worked fine. Created a separate branch, configured for mysql, try with that:

https://github.com/mstahv/spring-boot-spatial-example/tree/mysql

**Comment by punit412** [comment]
@mstahv I have tried with your build only. and found the same issue again having latest hibernate version - 5.2.4.Final and Mysql - 5.7.12. Might be it is not related to the MySQL version.

**Comment by mstahv** [comment]
Did you try with the exact branch I just referred or with something else? Latest hibernate version is 5.2.10.Final and it works just fine for me. I can't debug an arbitrary project of yours with these details.

If you want somebody to debug your application, you should look into our services https://vaadin.com/pricing

**Comment by pushpanktugnawat** [comment]
@mstahv a quick help did u just changed the hibernate version or you have done any code based changes as I have just checked didn't find any such changes so if i am missing something than please let me know.

**Comment by punit412** [comment]
@mstahv Thanks for your time and efforts. I really appreciate your work. My issue is resolved now.

**Comment by mstahv** [comment]
Awesome! Would you share the solution, so @pushpanktugnawat would get it as well?
